### ISSUE TITLE
AMP not disabled if opened in a new tab

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/DisableAMP#10] opened 2020-02-03 16:00 UTC

**Comment by ameshkov** [comment] 2020-02-07 15:33
Good bug, thank you for reporting it!

**Comment by Oizaro** [comment] 2020-05-17 18:21
@ameshkov Could you try to reproduce again only the first issue? If I open an AMP url on a new tab from previous one, extension work as usual.

**Comment by Oizaro** [comment] 2020-05-17 18:22
...

**Comment by mehta1190** [comment] 2020-05-18 10:57
@Oizaro, @ameshkov  I tried again and can confirm that when opening in a new tab, DisableAMP works only **partially**. It in fact works in the same way as you said in #17. Just like there is a /amp/ remaining in the url for which you made a commit, different sites when opened in new tab continue to contain such different remnants, which are otherwise absent when opened in the same tab. I am mentioning below few such examples, with both when opened in same tab(working OK) and in new tab(working not so nicely).
1. https://timesofindia.indiatimes.com/india/live-updates-lockdown-4-guidelines-and-coronavirus-in-india/liveblog/75796010.cms
https://timesofindia.indiatimes.com/india/live-updates-lockdown-4-guidelines-and-coronavirus-in-india/amp_liveblog/75796010.cms

2.https://www.indiatoday.in/india/story/cyclone-amphan-intensifies-extremely-severe-storm-odisha-bengal-alert-update-news-rain-1679072-2020-05-18
https://www.indiatoday.in/amp/india/story/cyclone-amphan-intensifies-extremely-severe-storm-odisha-bengal-alert-update-news-rain-1679072-2020-05-18

3.https://indianexpress.com/article/india/coronavirus-india-news-live-updates-today-mha-lockdown-4-guidelines-india-covid-19-corona-cases-tracker-6414793/
https://indianexpress.com/article/india/coronavirus-india-news-live-updates-today-mha-lockdown-4-guidelines-india-covid-19-corona-cases-tracker-6414793/lite/

4.https://m.economictimes.com/news/economy/indicators/goldman-sees-worst-india-recession-with-45-second-quarter-slump/articleshow/75796510.cms
https://m.economictimes.com/news/economy/indicators/goldman-sees-worst-india-recession-with-45-second-quarter-slump/amp_articleshow/75796510.cms

5.https://www.thehindu.com/news/national/india-coronavirus-lockdown-may-18-2020-live-updates/article31611813.ece
https://www.thehindu.com/news/national/india-coronavirus-lockdown-may-18-2020-live-updates/article31611813.ece/amp/

6.https://wap.business-standard.com/article/current-affairs/coronavirus-india-live-updates-lockdown-4-guidelines-total-covid-19-cases-death-toll-statewise-corona-vaccine-maharashtra-delhi-usa-china-latest-news-120051800086_1.html
https://wap.business-standard.com/article-amp/current-affairs/coronavirus-india-live-updates-lockdown-4-guidelines-total-covid-19-cases-death-toll-statewise-corona-vaccine-maharashtra-delhi-usa-china-latest-news-120051800086_1.html

7.https://www.ndtv.com/india-news/coronavirus-5-242-cases-in-india-in-24-hours-biggest-one-day-spike-total-cases-cross-96-000-mark-over-3-000-deaths-2230536
https://www.ndtv.com/india-news/coronavirus-5-242-cases-in-india-in-24-hours-biggest-one-day-spike-total-cases-cross-96-000-mark-over-3-000-deaths-2230536?amp=1

8.https://www.firstpost.com/health/coronavirus-outbreak-live-updates-covid-19-india-today-lockdown-4-extended-migrant-workers-death-count-cases-uttar-pradesh-rajasthan-maharashtra-goa-latest-news-8377101.html
https://www.firstpost.com/health/coronavirus-outbreak-live-updates-covid-19-india-today-lockdown-4-extended-migrant-workers-death-count-cases-uttar-pradesh-rajasthan-maharashtra-goa-latest-news-8377101.html/amp

You can notice that in 2nd set of links there is /amp/ in middle,/amp/ at end,-amp, amp-, /lite/,?amp=1 etc in different sites. So stripping one such element in url wont fix for all.

**Comment by Oizaro** [comment] 2020-05-18 12:29
@mehta1190 

Ok, thanks for better explanation. In practice your links are afflicted by a different form of persistance.

The problem is finding a generic link that disable amp.

**Comment by Oizaro** [comment] 2020-05-20 19:08
New tab fix:

https://github.com/AdguardTeam/DisableAMP/pull/19

**Comment by Oizaro** [comment] 2020-05-21 18:43
@mehta1190 https://mega.nz/file/0V1BnSaA#AQ-bvuh2ZqMZ0-9Yiw5mvb8T8fmRoPOYR5Jjy-f6JG8

This is a link to test build that includes both fixes. If you want to try it:

- Download the archive and unzip it somewhere.
- Close browser and uninstall the previous AMP extension from adguard.
- From the same location click on "install new extension" - "navigate", and select file "disable-amp.user" and install this test build.

Try it and report here your results.

**Closed** 2024-10-29 11:14 UTC
Labels: bug, Resolution: Won't Do, Status: Resolved, Priority: P3
